// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg153PJ6LuKTq7eUQ9zzQCccxC70tYLnw',
    appId: '1:369613593961:web:15094dde6a0e0f65db31f8',
    messagingSenderId: '369613593961',
    projectId: 'ctse-lab-sunday',
    authDomain: 'ctse-lab-sunday.firebaseapp.com',
    storageBucket: 'ctse-lab-sunday.appspot.com',
    measurementId: 'G-8S7QCXVSKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBlvlpzHm2tOK2dx8kl3w0eSw0ZK1TZO4',
    appId: '1:369613593961:android:e474b5f983b63c0fdb31f8',
    messagingSenderId: '369613593961',
    projectId: 'ctse-lab-sunday',
    storageBucket: 'ctse-lab-sunday.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDktzbXwDGBMmp1V8VCd7sGWq16Zyv6nFA',
    appId: '1:369613593961:ios:e8499de0b9fc5744db31f8',
    messagingSenderId: '369613593961',
    projectId: 'ctse-lab-sunday',
    storageBucket: 'ctse-lab-sunday.appspot.com',
    iosClientId: '369613593961-f3q1o6j5voe1jpkurdd967asc42e6998.apps.googleusercontent.com',
    iosBundleId: 'com.example.labActivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDktzbXwDGBMmp1V8VCd7sGWq16Zyv6nFA',
    appId: '1:369613593961:ios:e8499de0b9fc5744db31f8',
    messagingSenderId: '369613593961',
    projectId: 'ctse-lab-sunday',
    storageBucket: 'ctse-lab-sunday.appspot.com',
    iosClientId: '369613593961-f3q1o6j5voe1jpkurdd967asc42e6998.apps.googleusercontent.com',
    iosBundleId: 'com.example.labActivity',
  );
}
